<a href="https://colab.research.google.com/github/AfsanaBrishty/Machine-Learning-and-Deep-Learning-with-Python/blob/main/Save_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

In [9]:
import pickle

binary file create hobe. 'wb' for write mode and binary file

In [10]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

'rb' for read mode and binary file

In [12]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [13]:
mp.predict([[5000]])

array([859554.79452055])

In [15]:
pip install joblib

In [16]:
from sklearn.externals import joblib

In [17]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [18]:
mj = joblib.load('model_joblib')

In [19]:
mj.predict([[5000]])

array([859554.79452055])

In [20]:
mj.coef_

array([135.78767123])

In [21]:
mj.intercept_

180616.43835616432